apiVersion: v1
kind: Service
metadata:
  name: {{ include "rails.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rails.name" . }}
    helm.sh/chart: {{ include "rails.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.webpackDevServer.enabled }}
    - port: {{ .Values.webpackDevServer.port }}
      targetPort: webpack
      protocol: TCP
      name: webpack
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
